version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodemy-image
    container_name: nodemy-container
    restart: unless-stopped
    env_file: .env
    environment:
      - JWT_SECRET=$JWT_SECRET
      - SENDGRID_API_KEY=$SENDGRID_API_KEY
      - HOST=$HOST
      - MONGO_USERNAME=$MONGO_USERNAME
      - MONGO_PASSWORD=$MONGO_PASSWORD
      - MONGO_HOSTNAME=db
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DB
      - PHASE=$PHASE
    ports:
      - "80:8080"
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    networks:
      - app-network
    command: ./wait-for.sh db:27017 -- /home/node/app/node_modules/.bin/nodemon src/app.js

  db:
    image: mongo
    container_name: nodemy-db
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    volumes:
      - dbdata:/data/db
    networks:
      - app-network
      
networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
  node_modules:
